apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongodb-config-file: |
    systemLog:
      verbosity: 2
 # Configuración de almacenamiento de datos de MongoDB
    storage:
      dbPath: /data/db
# Configuración de red de MongoDB
    net:
      bindIp: 0.0.0.0
      port: 27017
# Configuración de seguridad de MongoDB
    security:
      authorization: enabled