apiVersion: v1
kind: Service
metadata:
  name: hab-service
spec:
  selector:
    app: habitacion
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: habitacion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habitacion
  template:
    metadata:
      labels:
        app: habitacion
    spec:
      containers:
        - name: habitacion-api
          image: Hab_Rest
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://admin:${process.env.MONGO_DB_PASSWORD}@hotel.tk6bla6.mongodb.net/Hotel?retryWrites=true&w=majority'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
