apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: YWRtaW4=  # base64-encoded 'admin'
  mongodb-root-password: MTIzNDU=  # base64-encoded '12345'

